apiVersion: v1
kind: Secret
metadata:
  name: blog-backend-secrets
  namespace: blog-application
  labels:
    app: blog-backend
    env: production
type: Opaque
data:
  # Base64 encoded values (echo -n 'value' | base64)
  SECRET_KEY: YXBwbGVpc3JlZA==  # appleisred
  MONGO_USERNAME: YWRtaW4=       # admin
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=  # password123
