apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog-frontend.fullname" . }}-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-frontend.labels" . | nindent 4 }}
    app: {{ .Values.frontend.name }}
    version: {{ .Values.frontend.image.tag }}
    component: frontend
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "blog-frontend.selectorLabels" . | nindent 6 }}
      app: {{ .Values.frontend.name }}
      version: v1
  template:
    metadata:
      labels:
        {{- include "blog-frontend.selectorLabels" . | nindent 8 }}
        env: {{ .Values.global.environment }}
        app: {{ .Values.frontend.name }}
        version: v1
    spec:
      containers:
        - name: {{ .Values.frontend.name }}-container
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "blog-frontend.fullname" . }}-configmap
                optional: false
          {{- if .Values.healthCheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readinessProbe.httpGet.path }}
              port: {{ .Values.healthCheck.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.livenessProbe.httpGet.path }}
              port: {{ .Values.healthCheck.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.livenessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
