apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-frontend.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-frontend.labels" . | nindent 4 }}
    app: {{ .Values.frontend.name }}
    env: {{ .Values.global.environment }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
  selector:
    {{- include "blog-frontend.selectorLabels" . | nindent 4 }}
    app: {{ .Values.frontend.name }}
    version: v1
