apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.frontend.name }}
    component: frontend
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.frontend.name }}
    version: {{ .Values.frontend.image.tag }}
