apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-backend.labels" . | nindent 4 }}
    component: backend
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "blog-backend.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "blog-backend.selectorLabels" . | nindent 8 }}
        component: backend
        version: {{ .Values.backend.image.tag | quote }}
    spec:
      # Init container runs before the main application container
      initContainers:
      - name: db-seeder
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        command: ["node", "seedAll.js"]
        env:
        # Secrets (sensitive data)
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secrets
              key: SECRET_KEY
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secrets
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secrets
              key: MONGO_PASSWORD
        # Build MONGO_URL from components
        - name: MONGO_URL
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DATABASE)?authSource=$(MONGO_AUTH_SOURCE)"
        envFrom:
          - configMapRef:
              name: {{ .Values.backend.name }}-configmap
              optional: false
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      # Main application container
      containers:
        - name: {{ .Values.backend.name }}-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
          # Secrets (sensitive data)
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.name }}-secrets
                key: SECRET_KEY
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.name }}-secrets
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.name }}-secrets
                key: MONGO_PASSWORD
          # Build MONGO_URL from components
          - name: MONGO_URL
            value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DATABASE)?authSource=$(MONGO_AUTH_SOURCE)"
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.name }}-configmap
                optional: false
          {{- if .Values.healthCheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readinessProbe.httpGet.path }}
              port: {{ .Values.healthCheck.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.livenessProbe.httpGet.path }}
              port: {{ .Values.healthCheck.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
