{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    purpose: application
    environment: {{ .Values.global.environment }}
    team: backend
    project: blog-k8s-deployment
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/component: backend
  annotations:
    project.maintainer: "{{ .Values.global.maintainer }}"
    project.repository: "{{ .Values.global.repository }}"
    project.course: "{{ .Values.global.course }}"
    project.date: "{{ .Values.global.projectDate }}"
{{- end }}
