apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.backend.name }}
    component: backend
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.backend.name }}
    version: {{ .Values.backend.image.tag }}
