# Frontend Service Values
# Maintainer: PRABESH MAGAR
# Repository: mprabesh/CBD-3324-k8s-final

# Override name of the chart
nameOverride: ""

# Override the full name of the resources
fullnameOverride: ""

global:
  environment: production
  maintainer: "PRABESH MAGAR"
  repository: "mprabesh/CBD-3324-k8s-final"
  course: "CBD-3324"
  projectDate: "2025-08-14"

# Namespace Configuration
namespace:
  name: blog-frontend
  create: true

# Frontend Configuration
frontend:
  name: blog-frontend
  image:
    repository: magarp0723/blogapp-frontend
    tag: v9
    pullPolicy: IfNotPresent
  
  replicas: 3
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
  
  ingress:
    enabled: true
    host: blog.local
    path: /
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  # Environment variables
  env:
    VITE_API_URL: "http://blog-backend-service.blog-backend.svc.cluster.local:8081"
    BACKEND_URL: "http://blog-backend-service.blog-backend.svc.cluster.local:8081"
    NODE_ENV: "production"
    NGINX_PORT: "80"
    API_BASE_URL: "/api"
    APP_VERSION: "v1.0.0"

# Network Policy
networkPolicy:
  enabled: true
  
# Health Checks
healthCheck:
  enabled: true
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
