{{- if .Values.mongodb.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-service
  namespace: {{ .Values.namespaces.database }}
  labels:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
  annotations:
    project.maintainer: "{{ .Values.global.maintainer }}"
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
{{- end -}}
