apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: blog-database
  labels:
    app: mongodb
    env: production
type: Opaque
data:
  # Base64 encoded values (echo -n 'value' | base64)
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=       # admin
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123
