{{- if .Values.security.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.secrets.mongodb.name }}
  namespace: {{ .Values.namespaces.database }}
  labels:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  annotations:
    project.maintainer: "{{ .Values.global.maintainer }}"
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.security.secrets.mongodb.data.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.security.secrets.mongodb.data.MONGO_INITDB_ROOT_PASSWORD }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.secrets.backend.name }}
  namespace: {{ .Values.namespaces.backend }}
  labels:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  annotations:
    project.maintainer: "{{ .Values.global.maintainer }}"
type: Opaque
data:
  SECRET_KEY: {{ .Values.security.secrets.backend.data.SECRET_KEY }}
  MONGO_USERNAME: {{ .Values.security.secrets.backend.data.MONGO_USERNAME }}
  MONGO_PASSWORD: {{ .Values.security.secrets.backend.data.MONGO_PASSWORD }}
{{- end -}}
