{{- if .Values.frontend.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  annotations:
    project.maintainer: "{{ .Values.global.maintainer }}"
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-app
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog-app
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.name }}-config
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- if .Values.frontend.healthChecks.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthChecks.livenessProbe.path }}
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.healthChecks.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthChecks.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.frontend.healthChecks.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthChecks.readinessProbe.path }}
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.healthChecks.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthChecks.readinessProbe.periodSeconds }}
          {{- end }}
{{- end -}}
