apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-database.labels" . | nindent 4 }}
    component: database
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      {{- include "blog-database.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      labels:
        {{- include "blog-database.selectorLabels" . | nindent 8 }}
        component: database
        version: {{ .Values.mongodb.image.tag | quote }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.service.targetPort }}
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.name }}-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.name }}-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.env.MONGO_INITDB_DATABASE | quote }}
          {{- if .Values.mongodb.persistence.enabled }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: {{ .Values.mongodb.persistence.mountPath }}
          {{- else }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          {{- end }}
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.name }}-pvc
      {{- else }}
      volumes:
        - name: mongodb-data
          emptyDir: {}
      {{- end }}
