{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.mongodb.name }}
    component: database
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
