apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-database.labels" . | nindent 4 }}
    component: database
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "blog-database.selectorLabels" . | nindent 4 }}
    component: database
