apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: blog-cache
  labels:
    app: redis
    env: production
  annotations:
    project.maintainer: "PRABESH MAGAR"
    project.repository: "mprabesh/CBD-3324-k8s-final"
    project.component: "cache"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        env: production
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
